coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "tests/"
  - "conftest.py"
  - "__pycache__/"
  - "src/shared_context_server/scripts/dev.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
