name: CI
on:
  push: { branches: ["**"] }
  pull_request:

env:
  # Test environment variables to prevent startup crashes
  API_KEY: "test-api-key-for-ci-only"
  DATABASE_URL: "sqlite:///:memory:"
  ENVIRONMENT: "testing"
  JWT_SECRET_KEY: "test-jwt-secret-key-for-ci-only-not-for-production"
  JWT_ENCRYPTION_KEY: "3LBG8-a0Zs-JXO0cOiLCLhxrPXjL4tV5-qZ6H_ckGBY="

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - python-version: "3.12"
            is-main: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv with cache
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --dev

      - name: Pre-commit (all hooks)
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Security audit
        run: uv run pip-audit

      - name: Test with coverage
        run: uv run pytest --cov=src --cov-report=xml --cov-report=term-missing -q --maxfail=3 --tb=short

      # Upload only once (on the main Python job) to avoid duplicates
      - name: Check coverage file exists
        if: matrix.is-main
        run: ls -la coverage.xml

      - name: Upload coverage to Codecov
        if: matrix.is-main
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unit
          name: ubuntu-${{ matrix.python-version }}
          fail_ci_if_error: false

  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv with cache
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --dev

      - name: WAL/Schema smoke test
        run: uv run pytest tests/test_smoke.py -v
        env:
          API_KEY: "test-api-key-for-ci-smoke-test"
          DATABASE_URL: "sqlite:///./test_smoke.db"
          ENVIRONMENT: "development"
          JWT_SECRET_KEY: "test-jwt-secret-key-for-smoke-test-only"
