name: CI
on:
  push: { branches: ["**"] }
  pull_request:

env:
  # Test environment variables to prevent startup crashes
  API_KEY: "test-api-key-for-ci-only"
  DATABASE_PATH: ":memory:"
  ENVIRONMENT: "test"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}
      
      - name: Install uv
        run: pipx install uv
      
      - name: Sync dependencies
        run: uv sync --dev
      
      - name: Lint check (ruff)
        run: uv run ruff check .
        
      - name: Format check (ruff)
        run: uv run ruff format --check .
      
      - name: Type check (mypy)
        run: uv run mypy src
        
      - name: Test suite
        run: uv run pytest -q --maxfail=3 --tb=short

  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
      
      - name: Install uv
        run: pipx install uv
      
      - name: Sync dependencies
        run: uv sync --dev
        
      - name: WAL/Schema smoke test
        run: uv run pytest tests/test_smoke.py -v
        env:
          API_KEY: "test-api-key-for-ci-smoke-test"
          DATABASE_PATH: "./test_smoke.db"
          ENVIRONMENT: "test"